name: Publish Docker Images

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  DJANGO_APP_DOCKER_REPOSITORY: react-django-infra

jobs:
  publish-django-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_IAM }} # provisioned by react-django-infra
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: backend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.DJANGO_APP_DOCKER_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }} # TODO: use semver tags
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG