name: Publish Docker Images

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

env:
  DJANGO_APP_DOCKER_REPOSITORY: web-apps-infra

jobs:
  publish-django-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # provisioned by react-django-infra
          # module.github-oidc.oidc_role
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }} 
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: backend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.DJANGO_APP_DOCKER_REPOSITORY }}
          IMAGE_TAG: "v0.0.1_test"
          # IMAGE_TAG: ${{ github.sha }} # TODO: use semver tags
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f dockerfiles/backend.Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG