name: Run backend lint

on:
  pull_request:
    paths:
    - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://black.readthedocs.io/en/stable/integrations/github_actions.html
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./backend"

