name: Run frontend lint

on:
  pull_request:
    paths:
    - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: yarn install
        working-directory: frontend
        run: yarn install
      - name: yarn lint
        working-directory: frontend
        run: yarn lint